[project]
name = "murf-hackathon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.12.0",
    "beautifulsoup4>=4.13.4",
    "black>=25.1.0",
    "customtkinter>=5.2.2",
    "deep-translator>=1.11.4",
    "easyocr>=1.7.2",
    "googletrans>=4.0.2",
    "httpx>=0.28.0",
    "keyboard>=0.13.5",
    "langdetect>=1.0.9",
    "lxml>=6.0.0",
    "mouse>=0.7.1",
    "murf>=2.0.0",
    "mypy>=1.17.0",
    "nltk>=3.9.0",
    "numpy>=2.3.1",
    "openai>=1.97.0",
    "opencv-python>=4.11.0",
    "pandas>=2.3.1",
    "pillow>=11.3.0",
    "plyer>=2.1.0",
    "psutil>=7.0.0",
    "pyaudio>=0.2.14",
    "pyautogui>=0.9.54",
    "pydub>=0.25.1",
    "pygame>=2.6.1",
    "pypdf>=5.8.0",
    "pypdf2>=3.0.1",
    "pystray>=0.19.5",
    "pytest>=8.4.1",
    "pytest-asyncio>=1.1.0",
    "python-docx>=1.2.0",
    "python-dotenv>=1.1.1",
    "python-pptx>=1.0.0",
    "pytube>=15.0.0",
    "pywin32>=311",
    "pyyaml>=6.0.2",
    "requests>=2.32.0",
    "ruff>=0.12.4",
    "scikit-image>=0.25.2",
    "scipy>=1.16.0",
    "selenium>=4.34.0",
    "sounddevice>=0.5.0",
    "speechrecognition>=3.14.0",
    "textblob>=0.19.0",
    "tkinter-tooltip>=3.1.0",
    "torch>=2.7.1",
    "torchvision>=0.22.1",
    "tqdm>=4.67.1",
    "trio>=0.30.0",
    "trio-websocket>=0.12.2",
    "watchdog>=6.0.0",
    "webrtcvad>=2.0.10",
    "websocket-client>=1.8.0",
    "windows-curses>=2.4.1",
    "xlsxwriter>=3.2.0",
    "youtube-transcript-api>=1.1.1",
    "yt-dlp>=2025.6.30",
]
